const NEWPROFILE_ROUTES = {
  DELETION: {
    MAIN: "NEWPROFILE_ROUTES_MAIN",
    INFO: "NEWPROFILE_ROUTES_INFO",
    CONFIRM: "NEWPROFILE_ROUTES_CONFIRM",
    ROUTER: "NEWPROFILE_ROUTES_ROUTER"
  } as const
} as const;

export default NEWPROFILE_ROUTES;
